# Generated by Django 4.2.21 on 2025-05-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("leave_id", models.CharField(max_length=30, unique=True)),
                ("leave_date", models.DateField()),
                ("leave_reason", models.TextField(blank=True, null=True)),
                (
                    "leave_status",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="courses.course"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "record_id",
                    models.AutoField(
                        db_column="record_id", primary_key=True, serialize=False
                    ),
                ),
                ("date", models.DateField(verbose_name="考勤日期")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "出席"),
                            ("absent", "缺席"),
                            ("approved_leave", "已批准请假"),
                        ],
                        default="absent",
                        max_length=20,
                        verbose_name="考勤状态",
                    ),
                ),
                (
                    "scan_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="签到时间"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="courses.course",
                    ),
                ),
                (
                    "leave_request",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="attendance.leaverequest",
                        verbose_name="关联请假申请",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="users.student"
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤记录",
                "verbose_name_plural": "考勤记录",
                "indexes": [
                    models.Index(
                        fields=["student", "course", "date"],
                        name="idx_student_course_date",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="attendance",
            constraint=models.UniqueConstraint(
                fields=("student", "course", "date"), name="unique_student_course_date"
            ),
        ),
    ]
